FROM httpd:latest
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/MidhunAravindan/terminal-portfolio.git /usr/local/apache2/htdocs/
EXPOSE 80
CMD ["httpd-foreground"]